name: ci-email
on:
  pull_request:
    branches:
    - master
    paths:
    - 'send_email/*'
    - '.github/workflows/ci-email.yaml'

jobs:
#stage
#building app
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        SHA=${GITHUB_SHA:0:7}
        APP=${GITHUB_REPOSITORY#*/}
        DOCKER_URL=${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPO }}/${APP}/${APP}-email:${SHA}
        cd send_email
        docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker build . --no-cache -f Dockerfile -t ${DOCKER_URL}
        docker push ${DOCKER_URL}
#deploy to Kubernetes       
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
      id: setcontext    
    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v1
      with:
        namespace: 'default'
        container-registry-url: ${{ secrets.REGISTRY_URL }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: 'docker-registry-secret'
      id: create-secret   
    - name: Set OpenstackPullSecrets
      uses: azure/k8s-create-secret@v1
      with:
        namespace: 'default'
        secret-type: 'generic'
        arguments:  --from-literal=email-password=${{ secrets.VENTUS_EMAIL_PASSWORD }} --from-literal=email-address=${{ secrets.VENTUS_EMAIL }}
        secret-name: email-credentials
    - name: Deploy
      run: |
        SHA=${GITHUB_SHA:0:7}
        APP=${GITHUB_REPOSITORY#*/}
        DOCKER_URL=${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPO }}/${APP}/${APP}-email:${SHA}
        cd send_email
        sed -i "s,IMG,${DOCKER_URL},g" deployment.yaml
        kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "docker-registry-secret"}]}'
        kubectl apply -f deployment.yaml